repos:
  - repo: local
    hooks:
      - id: stylua
        name: stylua
        entry: stylua
        language: system
        types: [lua]
      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        types: [nix]
      - id: tombi
        name: tombi
        entry: tombi format
        language: system
        types: [toml]
      - id: prettier
        name: prettier
        entry: prettier --write
        language: system
        types: [yaml]
      - id: shfmt
        name: shfmt
        entry: shfmt -w -i 2 -ci -bn
        language: system
        types: [shell]
